name: Deploy Wrangler

on:
  workflow_dispatch:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./wrangler

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Customize toml-file
        env:
          STELLAR_NETWORK: ${{ secrets.STELLAR_NETWORK }}
          HORIZON_URL: ${{ secrets.HORIZON_URL }}
          TURRET_ADDRESS: ${{ secrets.TURRET_ADDRESS }}
          TURRET_FUNCTION_RUNNER_URL: ${{ secrets.TURRET_FUNCTION_RUNNER_URL }}
          WRANGLER_ACCOUNT_ID: ${{ secrets.WRANGLER_ACCOUNT_ID }}
          WRANGLER_WORKER_NAME: ${{ secrets.WRANGLER_WORKER_NAME }}
          WRANGLER_META: ${{ secrets.WRANGLER_META }}
          WRANGLER_TX_FUNCTIONS: ${{ secrets.WRANGLER_TX_FUNCTIONS }}
          WRANGLER_XLM_FEE_MIN: ${{ secrets.WRANGLER_XLM_FEE_MIN }}
          WRANGLER_XLM_FEE_MAX: ${{ secrets.WRANGLER_XLM_FEE_MAX }}
          WRANGLER_UPLOAD_DIVISOR: ${{ secrets.WRANGLER_UPLOAD_DIVISOR }}
          WRANGLER_RUN_DIVISOR: ${{ secrets.WRANGLER_RUN_DIVISOR }}
        run: npm run init

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.WRANGLER_API_TOKEN }}
          workingDirectory: wrangler
